---
#========================================Clear Chat Automatically===============================
#   ██████╗██╗  ██╗ █████╗ ████████╗   ██████╗██╗     ███████╗ █████╗ ███╗   ██╗███████╗██████╗
#  ██╔════╝██║  ██║██╔══██╗╚══██╔══╝  ██╔════╝██║     ██╔════╝██╔══██╗████╗  ██║██╔════╝██╔══██╗
#  ██║     ███████║███████║   ██║     ██║     ██║     █████╗  ███████║██╔██╗ ██║█████╗  ██████╔╝
#  ██║     ██╔══██║██╔══██║   ██║     ██║     ██║     ██╔══╝  ██╔══██║██║╚██╗██║██╔══╝  ██╔══██╗
#  ╚██████╗██║  ██║██║  ██║   ██║     ╚██████╗███████╗███████╗██║  ██║██║ ╚████║███████╗██║  ██║
#  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝      ╚═════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝
#  ===============================================================================================
#  * This is free software: You can redistribute it and/or modify!
#  * This file is licensed under the  GNU Affero General Public License.(C)2020 GodWeedZao

#set Clear Chat Automatically (if you set this to false, chat does not clear Automatically!)
Auto-Clean: true
#the timer for clear chat if you set Auto-Clean to true.
#each 1 second = 20 tick (default is 120 second = 2400)
Timer: 2400
...